### ISSUE TITLE
Apps that use pkginfo fail.

### ISSUE THREAD

**Issue by jaredallard** [nexe/nexe#110]
Because hard coding fs was never any easier! 

Any application that uses the npm module `pkginfo` fails because of it's hard dependency on the use of fs for obtaining module info, which causes a serious issue for nexe because we don't have anything but one file.

The only solution I can think of is perhaps acting like the module if it arises? But that doesn't solve this problem in the long term.

**Comment by LorenzGardner** [comment]
Some things just won't work out of the box. And that is probably ok.

the workaround is to add the package.json file you are interested in to the embedded list, and get the info yourself.

Long term this kind goes under the feature of better embedded file handling. If we modified the fs behavior so that it check the path against an embedded list first we might be able to support this better. Of course you'd still need to add the package.json file to the embedded list. I don't think we'll ever have a good solution for dynamic requires / dynamic file loads.

**Comment by RainbowDashDC** [comment]
I agree, I'm going to work on getting fs behavior searching embedded list.

**Comment by calebboyd** [comment]
I implemented a similar fix to get bindings working. 
I basically did an ahead of time evaluation of the module. (to avoid redoing its functionality). Seems to work well. Perhaps I can take the same approach here.
