### ISSUE TITLE
What's the benefit of compiling into a single file?

### ISSUE THREAD

**Issue by timaschew** [nexe/nexe#235]
Another approach would be to create some kind of an installer which contains
- the node application and 
- the official node binary installer
  This would save the whole compilation time.

And what's about the license for nodejs? Is it allowed to compile your app together with node into a single file? Do you need to add/keep the origin nodejs license somewhere?

**Comment by oxygens** [comment]
Let me save you typing nodejs license into google: https://github.com/nodejs/node/blob/master/LICENSE

**Comment by jaredallard** [comment]
@timaschew Not packing the file would make this simply an installer, which, isn't a problem that warrants software as there's many solutions there.

We compile to a single file as it's the *easiest* way to bundle your application, not because it's inherently faster (though it could be or could not be). This allows us to easily hook into the node install script, and call our "file" as a core node lib essentially. This is why we need to compile, since we can't do this to an after binary.
