### ISSUE TITLE
Compile for windows, from linux

### ISSUE THREAD

**Issue by G047** [nexe/nexe#290]
Is it possible to compile a nexe binary for windows (x64) via ubuntu linux?

**Comment by calebboyd** [comment]
This isn't possible (yet). I worked on this with `xbin` and hope to add it to nexe soon!

**Comment by dlech** [comment]
What is the command line argument for this? I've tried the `--target` option, but it seems to be ignored.

**Comment by calebboyd** [comment]
Hi @dlech Thanks for the question, 

I'm going to reopen this because the work is still ongoing in beta
It requires multiple CI environments running builds and posting artifacts to github releases
And that work hasn't been finished yet. 

It'd probably be best to track it here. Once its done the --target option will control that

**Comment by calebboyd** [comment]
**Update!!**  - The target option will support any target in the latest github release

https://github.com/nexe/nexe/releases/tag/v2.0.0-rc.2

The cli will accept any part of the target as an option
eg.
From node 6.11.2 on Windows x64 
 - `-t mac` will give the target: `mac-x64-6.11.2`

Still working on CI for linux/alpine(static)

**Comment by calebboyd** [comment]
This is fully supported in rc.9

Closing!
