### ISSUE TITLE
[Question] NPM and plugin management with nexe

### ISSUE THREAD

**Issue by WoodySlum** [nexe/nexe#330]
This is a
 - [ ] Bug Report
 - [ ] Feature Request
 - [X] Other

Hi,

I'm developing a personal project.
I would like to obfuscate the core source code (using nexe), and be able to use external dependencies as plugins.
Here are my questions :
- Can I publish a nexe package into npm ? I mean the binary not source code
- Can I expose only one js file for public APIs which is able to communicate with the nexe binary ?

Here is a kind of architecture I would like to do :
- node-core (binary with nexe)
- npm dependencies, which could be installed through npm install (-g)

Thanks !

**Comment by CKarper** [comment]
* `nexe` is not a code security tool, and does not support obfuscation.   It will package it for you inside a binary, but it's still easily retrievable.
* You can absolutely publish a binary to npm.  npm is platform agnostic, it just happens to come packaged with node, and primarily serves node packages.  But since it's just using tarballs, you can put whatever you like in them.   You're probably "doing it wrong™" if you're trying to distribute binaries via npm though.
* That's not really how `nexe` works.  It's a complete version of the node engine with your code built in.  It wouldn't be for external programs/resources to use.  You're probably looking for [native addons](https://nodejs.org/api/addons.html).  A project like [`nan`](https://github.com/nodejs/nan) will be more helpful in that effort.
* A module packaged with `nexe` would be able to use dependencies in `node_modules`, just like any other node program. 😄

**Comment by WoodySlum** [comment]
Thanks the complete answer even if it's a little bit out of nexe's scope :)
