### ISSUE TITLE
Include native .node file in the generated binary

### ISSUE THREAD

**Issue by jgoux** [nexe/nexe#430]
This is a
 - [ ] Bug Report
 - [ ] Feature Request
 - [x] Other

Hello,

I'm trying to include the `oracledb.node` file generated after installing `oracledb` library inside my binary built with nexe.

I tried passing a `--native oracledb` option but it doesn't work.

I also tried to add it as a resource with `-r node_modules/**/build/Release/*.node` but it doesn't work either.

I have this error at runtime : 

```
oracledbCLib.Oracledb.prototype.newLob = function(iLob) {
             ^
TypeError: Cannot read property 'Oracledb' of null
```

So it's clear here that the native library isn't found.

What should I do?

Thanks a lot

- Platform(OS/Version): Debian 9
- Host Node Version: v8.9.1
- Target Node Version: v8
- Nexe version: 2.0.0-rc.22
- Python Version: 2.7.13

**Comment by calebboyd** [comment]
AFAICT `oracledb` relies on quite a bit of external configuration.

https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

Are you ensuring your destination machines have those files (correct version/architecture etc)?

**Comment by jgoux** [comment]
Yes it works well without compiling or when I compile with `pkg` (but then I have to keep the .node file along with the binary)

I wanted to try nexe to be able to put the `.node` extension inside the binary so I got only one final file. 😄

**Comment by calebboyd** [comment]
Yeah, thats a goal -- I'll follow up with this issue when I have something new

**Comment by coccyx** [comment]
I came to nexe after I ran into the same issues as @jgoux with pkg. As far as I can tell, just looking via `strings`, the `.node` (`pty.node` in my case) is not included in the resulting binary. Are there any workarounds? You mentioned fuse-box may have broken something. Happy to take a crack at fixing it before your planned fix using resolve-dependencies.  Looks like it worked at some point.

**Comment by bwin** [comment]
AFAIK it's not possible to package an app with native dependencies into one file.
(It's possible to package it, but it needs to unpack those dependencies at runtime. See workaraound  https://github.com/nexe/nexe/issues/411#issuecomment-336745180)

Node uses `dlopen` to load libraries (native dependencies) and it expects a filename. There is no way to make it accept a Buffer or start position and offset.

That makes this wontfix (even cantfix)!

What's possible though, is to automate the workaround.
Nexe would have to keep track of `dlopen`ed files and put this list into the nexe-executable's footer, which upon startup would extract these files and delete them on close.
Or without this list, we could iterate through all resources and extract all `.node` and `.so` and `.dll` files?

Even better might be, to strip away the path (like `node_modules/bcrypt/lib/binding`) and make sure the filename is unique.
(The paths/filenames would also have to be changed on callsite.)
That way they could be extracted to the .exe's path without needing to create a whole tree of dirs (and deleting them afterwards). Or maybe extract them to a newly created dir named `tmp` or `dynamic-dependencies` (and still delete this afterwards).

The automatic workaround would still not fix the issue, where an actual executable file is a dependency of a dependency. But the manual workaround can handle this.
In issue #411 there's an .exe-file bundled with a dependency and gets run with `child_process.execFile`.

**Comment by calebboyd** [comment]
@bwin In V2 we [used a mechanism](https://github.com/nexe/nexe/tree/79bcb753b462d5d87580f773c8024bcf89888076/src/bundling) which would rewrite `require('bindings')` and also any `require('*.node')` callsites to a shortened hash based filename, kind of like you've described.

But there were too many issues using fusebox for general node app bundling so `resolve-dependencies` is used now. It can identify binary requires but currently does nothing with them. It could also be used to identify files that depend on libraries like `bindings` and `node-pre-gyp` so they can be eagerly evaluated.

Some additional work could be done to support filtering and rewriting those files to hash based filenames. Writing out the native addons on startup if-not-exists and cleaning them up on exit. And possibly even at build time - fetching pre-builts for alternate platforms depending on the target.

This is why we're keeping the `native-addon` label around.

**Comment by bwin** [comment]
@calebboyd Thanks for taking the time to point that out.
Don't expect a PR from me anytime soon, this is currently not even a use-case of mine. I just looked at it, because it seemed interesting.

**Comment by meteorsnows** [comment]
Thanks you all for all the info. If that possible that copy .node manually into asar. Do Asar simplify the requirement of needed file name from dlopen?

**Comment by cris691** [comment]
What about, a simple solution, like a script that does the above described runtime unbundling. In other words:

1. Build MyApp with webpack (+node-loader) -> MyApp.js
2. Builld MyApp.js with nexe
3. Write MyAppLoader which does something like this:
```js
const nativeModules = fs.readdirSync('natives');
nativeModules.forEach(f => fs.writeFileSync(f.name, Buffer.from(f)));
const proc = child_process.spawn('MyApp');
proc.on('exit', () => {
  fs.readdirSync('.').forEach(f => {
   if ( f.name.endsWith('.node')) ) fs.unlink(f);
 });
});
```
4. Build MyAppLoader.js with nexe with -r /natives/*.node and -r MyApp
5. Celebrate, rejoice, multiply, migrate to promised land. 

Will this work? I'm thinking about doing this for a project, because I prefer nexe to the complexity of pkg.

*About the "pseudo"pseudo Node code above, you know what it means*

**Comment by calebboyd** [comment]
Yep, that'll [work](https://github.com/nexe/nexe/issues/430#issuecomment-490086514)

**Comment by cris691** [comment]
@calebboyd after considering this, I ended up just removing the 1 native module I needed (sharp, to convert images to webp) and for the release just switched back to using JPEG.  I could not get native modules to work with webpack (+ node-loader), symbol lookup errors. Maybe it was just a case of finessing the libvips configuration to make sure that the right version of that library is installed, but at that point i realized...A new set of native deps will need to be individually handled for every different platform. 

Nexe makes cross-platform simple, and this complicated it, so I cut it. Next I tried looking up the libwebp/cwebp.wasm files to use a web assembly version. But there were issues with the webassembly imports I would have had to figure out. Probably by recompiling the sources using emscripten.

Thinking about this issue of native modules, I really think wasm is the cross-platform way to go. Since it's a platform independent intermediate binary format that works with node, and can be loaded from a file system using fs, so it sounds like, as long as a native module dep can be somehow converted to a wasm dep, nexe will be fine. 

I really think nexe + node + wasm is the future of easy cross-platform. Well I hope so anyway!

Thanks for all your work on nexe, it's an awesome "makes my life easier" project! Awesome work!! 😃
