### ISSUE TITLE
Calling nexe@next from SSH

### ISSUE THREAD

**Issue by rahbari** [nexe/nexe#533]
I've been using ssh-promise to connect to a linux server and compile node using nexe with this command:

`await ssh.exec('cd app/ && node nexe')`

it was correctly working with nexe 2 but with 3 it seems nexe output (ora) **...starting** to stderr instead of stdout and execution is halted.

Even when I put it in silent mode nothing is included in package, although if I run this command in linux terminal it works correctly.

I tried changing directory using process.chdir('/root/app/'); and:
`await ssh.exec('node app/nexe')`

but still only node.js is packaged.

**Comment by rahbari** [comment]
After checking the code for a while I found this in options.js:

```
if (!process.stdin.isTTY) {
    return ''
}
```

I don't exactly know why it's there but it prevents compilation if call is not from terminal.

**Comment by calebboyd** [comment]
What is the contents of the file `app/nexe`?

**Comment by rahbari** [comment]
> This is expected behavior. It doesn't look like you're able to use the pty option of the SSH2 client that ssh-promise is using. If you used that I do not think there would be an issue.

Why should nexe return '' if it's not called from termianl?

> stderr is where program logs and diagnostics go, that will not be changing.

As name suggests stderr is for printing errors and stdout is for logs and debugs.

**Comment by rahbari** [comment]
> This is expected behavior. It doesn't look like you're able to use the `pty` option of the SSH2 client that ssh-promise is using. If you used that I do not think there would be an issue.
> 
> stderr is where program logs and diagnostics go, that will not be changing.
> 
> What is the contents of the file `app/nexe`?

**Comment by calebboyd** [comment]
If you have an input (`-i` or `--input` or `nexe input.js`) you should specify it and this issue will go away. Since it isn't provided explicitly AND you're not in a TTY. Nexe is expecting to get the input from stdin

Regarding stderr. All spinners print to stderr. stdout is generally piped to a file or another program which a spinner would completely wreck.

If you want to suppress the output you can pass `--silent` Nexe will provide an exit code (1) if there is an error. 

There may be an opportunity here to detect if stdin is empty, and in that case fallback to the package.json#main. But thats why we have betas 😂
