### ISSUE TITLE
Create node v12.11.0 build

### ISSUE THREAD

**Issue by zuohuadong** [nexe/nexe#675]
v12.11.0 is missing from the latest build which is "current" on the Node downloads page 👍

**Comment by ddavness** [comment]
At the moment, it's "blocked" because the tarball for v12.11.0 is incomplete - see:
- https://github.com/nodejs/node/issues/29709 
- https://github.com/nodejs/node/pull/29712

You should probably wait until v12.11.1 comes out, since node builds for nexe aren't the same as the regular node releases.
###### But since they're still missing v12.10.0, I don't know...
