### ISSUE TITLE
How do you package other files into the exe?

### ISSUE THREAD

**Issue by fresheneesz** [nexe/nexe#77]
If I want to package, say, images into the exe, or anything other than things that can be found by traversing the require dependency tree of the input file, how would you do that? Is that possible? If not, consider this a feature request : )

**Comment by LorenzGardner** [comment]
So I've been thinking a lot about this. 

My first thought it to do it like Qt does with the qrc stuff. Embed the file(s) into a char array in a c file and add it to the source to get linked in. The issue then becomes how do you access your embedded file from your node .js files bundled in your executable?

Well like Qt we would need a way to Accessor to grab the files. Ideally we'd modify node_file.cc so that the built in node fs module would just handle a special path. i.e. if the path fs is loading begins with ":/someFile.txt" it knows it is an embedded file and can handle it. While that would be the ideal behavior the result would be incredibly brittle and the monkey patch on that would be really hard to write and ensure it stays working across versions of node.

Alternatively we could add a new build in module, that would allow you to do a require("embedded") and then a simple .read would return a node buffer. This of course gets us a slightly more robust implementation but then if node changes they way its built in modules interact with process bindings your node_embedded.cc and embedded.js would break.

The simplest implementation wise is to add them to the bundle process where you in the nexe.js file add them inline as a base64 encoded string or something. Then take our custom require function and if the path is ":/someFile.txt" we know it is embeded and we can give back a node buffer with the decoded string.

The downside to all of these approaches is they don't work when not using nexe. i.e. running your app with "node index.js"

**Comment by RainbowDashDC** [comment]
I worked on a program called PHC-WIN and it had a similar method of loading files, but what we could do is have it look for the file locally _first_ then if it doesn't exist see if it's embeded, this would allow non-nexe compatability.

**Comment by calebboyd** [comment]
This is in `nexe@beta`

`nexe -r "public/**/*`

The files are serialized to js comments, encoded in base64. They are indexed for quicker retrieval and shimmed with fs.readFile and fs.readFileSync (currently)

Right now they only work with relative file paths. Plan to add resolved path removal for the process's current path.
