### ISSUE TITLE
Running inside scratch container

### ISSUE THREAD

**Issue by omerlh** [nexe/nexe#848]
**What happened**:
I built a binary using Nexe and tried to running it inside [scratch](https://hub.docker.com/_/scratch) container.
To my surprise it failed with a very cryptic error:

``` ---> Running in 85df6778dbe3
OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```

**What you expected to happen**:
Running as it should 

**How to reproduce it (as minimally and precisely as possible)**:
Build something with npx and try running inside scratch container

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version):
- Host Node Version:
- Target Node Version:
- Nexe version:
- Python Version:

**Comment by jaredallard** [comment]
Please post the `Dockerfile`, it looks like your entrypoint is malformed causing it to exec a shell before your program. That error message is not from nexe or node.js

**Comment by omerlh** [comment]
Looking at this [stackoverflow question](https://stackoverflow.com/a/55106860/4792970) I think there is a problem with dynamic linking.

This is my docker file:
```
FROM scratch

COPY app /

CMD ["/app"]
```

This ended up with a bit different error:

```
standard_init_linux.go:219: exec user process caused: no such file or directory
```

**Comment by wilmardo** [comment]
The node used probably isn't statically compiled (it isn't by default). To try with node fully static you can use this image:
https://github.com/LANsible/docker-nexe/blob/master/Dockerfile

and change to fully-static:
https://github.com/LANsible/docker-nexe/blob/master/Dockerfile#L46

Then try again with your app with the nexe within this image something like:

```Dockerfile
FROM localimage as nexe

RUN nexe --build --target alpine app.js


FROM scratch 

COPY --from nexe app /usr/local/bin/app

ENTRYPOINT ["/usr/local/bin/app"]
```

I do partially static since I have apps that use C node modules which require dynamic linking.
You can make dynamic apps work in scratch, you just need to add the linker and the C runtime:
https://github.com/LANsible/docker-zigbee2mqtt/blob/master/Dockerfile#L51

Going to scratch containers is a big, big rabbit hole though and tools like [sysdig](https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-for-Linux) are your friend. `sysdig image.name=<image>` and then running the image not working. Then search through the strace for clues.

I might write a blogpost someday about troubleshooting scratch containers and useful tips, let me know if there is interest :)

Some examples with nexe:

* https://github.com/LANsible/docker-zigbee2mqtt/blob/master/Dockerfile
* https://github.com/LANsible/docker-zwave2mqtt/blob/master/Dockerfile

Some scratch examples with C

* https://github.com/LANsible/docker-mosquitto/blob/master/Dockerfile
* https://github.com/LANsible/docker-nginx/blob/master/Dockerfile
* https://github.com/LANsible/docker-socat/blob/master/Dockerfile
