### ISSUE TITLE
Decompile exe file

### ISSUE THREAD

**Issue by ffbboy30** [nexe/nexe#901]
Hi,

I'm looking to find a solution to decompile an exe file. 
With an Hex editor I can see the file start with MZ and contain node.js or java file. 
I've tried to decompress with 7zip.
 Do you have some idea ? Thanks

**Comment by ffbboy30** [comment]
I've made a error with my question .
When I compile it not works the same as norma, it works a little bit speeder than my VS code.
That why I'm looking to go back to compare.
If it is not possible I don't care , it's a tiny problem.

I've another question in the exe I've found 
"./node_modules/ws/package.json":[58874,1234]
58874 is the offset ?
1234 the size file  ?

What that it means ?

**Comment by calebboyd** [comment]
>I've another question in the exe I've found
"./node_modules/ws/package.json":[58874,1234]

That line represents an entry in the nexe virtual file system manifest (its an implementation detail, the offset in the blob (not the binary itself) and byte length)

https://github.com/nexe/nexe/blob/0c7b942f7f30f604e5f91da015df5863c0bff0b3/src/fs/bundle.ts#L144

At build time your application's dependencies (on the build machine) are combined into an uncompressed blob and appended to the end of a mostly normal node.js binary. 

>When I compile it not works the same as norma, it works a little bit speeder than my VS code.

The file system calls are likely faster because the reads can share a descriptor as they seek through the blob.

**Comment by ffbboy30** [comment]
So if the file are listed correctly in the exe , Is possible to go back from the exe to the project to compare the both code if they are the same ?
Thanks

**Comment by calebboyd** [comment]
Yes, it's possible. But the methodology for doing so is not documented and subject to break.

**Comment by calebboyd** [comment]
Moving to a discussion thread - https://github.com/nexe/nexe/discussions/914
