### ISSUE TITLE
Error: Cannot find module './READY.js'

### ISSUE THREAD

**Issue by Default-01** [nexe/nexe#944]
When i compile the project everything seems to work, but once I move the exe out of the folder with the node-modules it seems to not work. then I get this error:

![image](https://user-images.githubusercontent.com/55616945/143301780-be855560-0c72-4472-bfe5-57c46add92e8.png)

When I move the exe back to the node-modules everything works again, Can I include the node-modules into the exe somehow?

**Comment by calebboyd** [comment]
Is `./websocket/handlers/index.js` requiring that file dynamically? 
Only if there is a specific static require statement.. eg `require('./READY.js')` will it work.

Otherwise you'll want to add the dynamically required files with `--resource websocket/handlers/**/*` glob patterns as a command line option.

**Comment by Default-01** [comment]
Thank you
